### ISSUE TITLE
File Verification Error After Download of Boost

### ISSUE THREAD

**Issue by ellestad** [pnlbwh/ukftractography#105]
File Verification Error After Download of Boost during build process. It tries to download from several other sources, but they all fail with a verification error.

> [ 45%] Performing download step (download, verify and extract) for 'Boost'
> -- verifying file...
>        file='/home/vhasfcellese/build/ukftractography/Boost-prefix/src/boost_1_55_0.tar.gz'
> -- MD5 hash of
>     /home/vhasfcellese/build/ukftractography/Boost-prefix/src/boost_1_55_0.tar.gz
>   does not match expected value
>     expected: '93780777cfbf999a600f62883bd54b17'
>       actual: 'd41d8cd98f00b204e9800998ecf8427e'
> -- File already exists but hash mismatch. Removing...

**Comment by ihnorton** [comment]
@ellestad I just did a successful clean build on CentOS 7 (with anaconda compiler toolchain 3). Maybe this was an intermittent network problem?

**Comment by ellestad** [comment]
Upon further examination, this is a problem with traffic filtering at our location, not anything to do with ukftractography.
