### ISSUE TITLE
Remove Kent Williams from project

### ISSUE THREAD

**Issue by hjmjohnson** [pnlbwh/ukftractography#109]
About 6 years ago Kent Williams worked in my lab and helped with ukftracography codebase. 
 Kent has a new position and is no longer working in medical imaging.  Please remove the (  Chaircrusher ) user from this project.

Hans

**Comment by ihnorton** [comment]
I don't see his user having access either to this repo or as a member of pnlbwh organization.

**Comment by ihnorton** [comment]
By the way I made you an admin on this repo.
