### ISSUE TITLE
Associate 3d-slicer-extension topic with the repository

### ISSUE THREAD

**Issue by jcfr** [pnlbwh/ukftractography#113]
Could you associate the `3d-slicer-extension` GitHub topic so that it is listed here: https://github.com/topics/3d-slicer-extension

To learn more about topic, read https://help.github.com/en/articles/about-topics

**Comment by jcfr** [comment]
cc: @ljod @tashrifbillah

**Comment by ljod** [comment]
@yrathi
(Thanks @jcfr. I don't control this repo. Yogesh is in charge)

**Comment by tashrifbillah** [comment]
I'll try to do it this week.

**Comment by jcfr** [comment]
Thanks. It should literally take less than 3s to execute :)

**Comment by tashrifbillah** [comment]
Done!

**Comment by tashrifbillah** [comment]
See [pnlbwh/ukftractography](https://github.com/topics/3d-slicer-extension?o=desc&s=updated) listed there.
