### ISSUE TITLE
Failed to clone repository: 'git://www.vtk.org/VTK.git'

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/ukftractography#124]
Hi @rmukh ,

Do you know if Kitware moved VTK.git?
I tried to build UKFTractography but it failed with the following:

```bash
[  8%] Performing download step (git clone) for 'VTK'
-- Downloading...
   dst='/home/tb571/tmp/ukfbuild/Boost-prefix/src/boost_1_70_0.tar.gz'
   timeout='none'
-- Using src='http://sourceforge.net/projects/boost/files/boost/1.70.0/boost_1_70_0.tar.gz'
fatal: remote error: access denied or repository not exported: /VTK.git
Cloning into 'VTK'...
fatal: remote error: access denied or repository not exported: /VTK.git
Cloning into 'VTK'...
fatal: remote error: access denied or repository not exported: /VTK.git
Cloning into 'VTK'...
-- Had to git clone more than once:
          3 times.
CMake Error at /home/tb571/tmp/ukfbuild/VTK-prefix/tmp/VTK-gitclone.cmake:66 (message):
  Failed to clone repository: 'git://www.vtk.org/VTK.git'


make[2]: *** [VTK-prefix/src/VTK-stamp/VTK-download] Error 1
make[1]: *** [CMakeFiles/VTK.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Cloning into 'zlib'...
```

Previously, we had trouble with hard-coded software path. If the publisher moves without redirecting the hyperlink, our software fails to find them.

**Comment by tashrifbillah** [comment]
Trouble experienced by @jarrett-rushmore 
Issue detected by @tashrifbillah 

(Issue https://github.com/pnlbwh/pnlpipe/issues/47)

**Comment by tashrifbillah** [comment]
Way to reproduce:
```bash
cd /tmp
git clone https://github.com/pnlbwh/ukftractography.git
mkdir ukfbuild
cd ukfbuild
cmake ../ukftractography
make -j 1
```

**Comment by tashrifbillah** [comment]
Hi @yrathi , this issue needs immediate attention. Someone cloning the master branch won't be able to build UKFTractography.

**Comment by tashrifbillah** [comment]
See https://vtk.org/Wiki/VTK/Building/Linux#Download:
> git clone https://gitlab.kitware.com/vtk/vtk.git

Given that, how do we have [`${git_protocol}://www.vtk.org/VTK.git`](https://github.com/pnlbwh/ukftractography/blob/60b29e8a702feaf0c1d9e0fb7cd6a1e62506c7c1/SuperBuild/External_VTK.cmake#L38) ?

**Comment by rmukh** [comment]
Solved by https://github.com/pnlbwh/ukftractography/pull/125
