### ISSUE TITLE
Slicer extension build fails on windows

### ISSUE THREAD

**Issue by pieper** [pnlbwh/ukftractography#129]
See: https://discourse.slicer.org/t/the-slicerdmri-extension-is-currently-unavailable/12276/11

**Comment by tashrifbillah** [comment]
PR #130

**Comment by jcfr** [comment]
I suggest to close this issue.

Looking at the dasboard for StablePreview see [here](http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=UKF)) seems to confirm this:

![image](https://user-images.githubusercontent.com/219043/93821438-8ea28e80-fc2c-11ea-9fbb-82b8fd7b19a6.png)

It is still failing with SlicerStable (see [here](http://slicer.cdash.org/index.php?project=Slicer4&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=UKF)) but I don't think we should put effort into it as we will soon release a new snapshot release and Slicer 5 is coming soon as well.
