### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by dazhangge-666** [pnlbwh/ukftractography#150]
I performed UKFTractography in my ubuntu20.04 with gcc/g++7 and when I input :
mkdir
cmake
make

it occured below:
[ 88%] Performing configure step for 'UKFTractography'
Not searching for unused variables given on the command line.
loading initial cache file /home/ubuntu/UKF/ukf_build/UKFTractography-prefix/tmp/UKFTractography-cache-Release.cmake
-- Setting C++ standard
-- Setting C++ standard - C++11
-- Configuring SEM CLI module: UKFTractography
-- Configuring SEM CLI module: ConvertVTK
-- Configuring SEM CLI module: fibertractdispersion
-- Configuring SEM CLI module: vtk2mask
-- Configuring SEM CLI module: vtkFilter
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/UKF/ukf_build/UKFTractography-build
[ 89%] Performing build step for 'UKFTractography'
[  1%] Generating UKF_GIT_HASH
fatal: not a git repository (or any of the parent directories): .git
make[5]: *** [ukf/CMakeFiles/_GEN_GITVER.dir/build.make:60: ukf/CMakeFiles/_GEN_GITVER] Error 128
make[4]: *** [CMakeFiles/Makefile2:1043: ukf/CMakeFiles/_GEN_GITVER.dir/all] Error 2
make[3]: *** [Makefile:141: all] Error 2
make[2]: *** [CMakeFiles/UKFTractography.dir/build.make:119: UKFTractography-prefix/src/UKFTractography-stamp/UKFTractography-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:123: CMakeFiles/UKFTractography.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

How could I solve it?

**Comment by tashrifbillah** [comment]
We extensively tested it on CentOS 7. Do not know about Ubuntu. Feel free to Google.

**Comment by tashrifbillah** [comment]
> I performed UKFTractography in my ubuntu20.04 with gcc/g++7 and when I input :
> mkdir
> cmake
> make

Actually, give me the full command you have used. I may be able to help.

**Comment by tashrifbillah** [comment]
You need to do:

```
cd ukftractography (it is the folder you cloned ukftractography into)
mkdir build
cd build
cmake ..
make -j 4
```

**Comment by dazhangge-666** [comment]
3Q very much.My final purpose is  batch processing UKFTractography automatically in my server.
But I unfortunately met some new bug without changing anything during "make" like this.



fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
CMake Error at /home/ubuntu/UKF/ukf_build/Eigen-prefix/tmp/Eigen-gitupdate.cmake:10 (message):
  Failed to get the hash for HEAD


make[2]: *** [CMakeFiles/Eigen.dir/build.make:96: Eigen-prefix/src/Eigen-stamp/Eigen-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:205: CMakeFiles/Eigen.dir/all] Error 2
make: *** [Makefile:95: all] Error 2


Secondly, the full commend that I input are : 
mkdir ukf_build
cd ukf_build
cmake ../ukftractography-master
make

**Comment by tashrifbillah** [comment]
What is `ukftractography-master` here? Is this the directory you have cloned this repository into?

**Comment by dazhangge-666** [comment]
Yes,I use the github to download the zip file in windowsOS,which names ukftractography-master.zip.Then I used scp command to upload it to ubuntu server.

**Comment by dazhangge-666** [comment]
hello I just stuck at this step.When I use the command "make -i", I could complete it.I only need to solve the "not a  git repository"
I need some help!
fatal: not a git repository (or any of the parent directories): .git
make[5]: *** [ukf/CMakeFiles/_GEN_GITVER.dir/build.make:60: ukf/CMakeFiles/_GEN_GITVER] Error 128
make[4]: *** [CMakeFiles/Makefile2:1043: ukf/CMakeFiles/_GEN_GITVER.dir/all] Error 2
make[3]: *** [Makefile:141: all] Error 2
make[2]: *** [CMakeFiles/UKFTractography.dir/build.make:119: UKFTractography-prefix/src/UKFTractography-stamp/UKFTractography-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:123: CMakeFiles/UKFTractography.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
(base) ubuntu@dmri:~/UKF/ukftractography-master/build$

**Comment by tashrifbillah** [comment]
User successfully cloned and installed it.
