### ISSUE TITLE
I got it !Maybe it is  really the problem of your git repository.Maybe you haven't update I guess.

### ISSUE THREAD

**Issue by dazhangge-666** [pnlbwh/ukftractography#152]
I copied a code from my Classmate.She performed it early and make successfully.Then I used the same command via her code which download early,I made it soomthly without error.Maybe you can try to download a new code from github for a new try.

**Comment by dazhangge-666** [comment]
thanks you very much,bro!

**Comment by jhlegarreta** [comment]
This issue seems uninformative of any problem with the tool. Should be closed.
