### ISSUE TITLE
[nrrd] nrrdLoad: trouble reading .nii.gz --> UKFTractography in pnlpipe docker container

### ISSUE THREAD

**Issue by kavandeloo97** [pnlbwh/ukftractography#160]
Hi there, I get an error when trying to run UKFTractography in the pnlpipe docker container (please advise, thank you in advance!): 

(pnlpipe3) [root@156c1c951699 dwi]# UKFTractography --dwiFile sub-HV153_ses-01_desc-UnXc_dwi_EdEp.nii.gz --maskFile sub-HV153_ses-01_desc-UnXc_dwi_maskQc.nii.gz --numThreads 8 --seedsPerVoxel 5 --recordTensors --freeWater --recordFreeWater --tracts ./sub-HV153_ses-01_desc-UnXc_dwi_EdEp.vtk 

Using the 2T simple model with free water estimation. Setting the default parameters accordingly:
"*": set by user
"-": default setting
- stoppingFA: 0.15
* seedingThreshold: 0.18
- Qm: 0.001
- Ql: 50
- Rs: 0.02
* stepLength: 0.3
* recordLength: 0.9
- Qw: 0.0015
* stoppingThreshold: 0.1
* seedsPerVoxel: 5
Found 8 cores on your system.
Running tractography with 8 thread(s).
Trouble reading sub-HV153_ses-01_desc-UnXc_dwi_EdEp.nii.gz: [nrrd] nrrdLoad: trouble reading "sub-HV153_ses-01_desc-UnXc_dwi_EdEp.nii.gz"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: couldn't parse "|q{B,$X!\*`wzfgw{[U;;sYwgg" as magic or beginning of any recognized format

ISignalData could not be loaded
UKFTractography: ITK ExceptionObject caught!

itk::ExceptionObject (0x55d24ad8a9e0)
Location: "unknown" 
File: /home/pnlbwh/pnlpipe/soft_dir/ukftractography/UKFTractography/UKFTractography.cxx
Line: 70
Description: itk::ERROR: ::LoadFiles failed with unknown error.

**Comment by tashrifbillah** [comment]
Hi Katie, it works with nrrd format only. Use [nhdr_write.py](https://github.com/pnlbwh/conversion/blob/master/conversion/nhdr_write.py) to write an associated nhdr file and provide `--dwiFile sub-HV153_ses-01_desc-UnXc_dwi_EdEp.nhdr`

**Comment by kavandeloo97** [comment]
Thanks!
