### ISSUE TITLE
Consider adding an extension named "Boost"

### ISSUE THREAD

**Issue by jcfr** [pnlbwh/ukftractography#2]
For an example, see https://github.com/chrismullins/ExtensionsIndex/commit/987fa3008e2b7f7f5ff49f80a4e6c736d66499f9

Since Boost is cmake-ified and needed solely at build time, it is possible to add it as an extension that will be downloaded/built without being distributed to the Slicer user.

**Comment by ihnorton** [comment]
No longer applicable, the boost code is disabled at least with Slicer build.
