### ISSUE TITLE
Defaults to writing uncompressed ascii vtk's

### ISSUE THREAD

**Issue by pnlbwh** [pnlbwh/ukftractography#39]
unless I use switch `-a`

    -a,  --writeAsciiTracts
         Write tract file as a VTK binary data file (default: 0)

and then it writes smaller binary vtk's.  The default should change and `--writeAsciiTracts` should turn on ascii, not binary.

**Comment by hjmjohnson** [comment]
I am nearly sure that this issue has been resolved.
