### ISSUE TITLE
No rule to make target `/usr/lib64/libwrap.so', needed by ConvertVTK

### ISSUE THREAD

**Issue by pnlbwh** [pnlbwh/ukftractography#46]
Hi guys
@Chaircrusher @hjmjohnson @reckbo ,

I've been trying to compile UKFTractography (stand alone) on our collaborator's machines at U Penn. 

It goes well for all the external source builds, until it hits the build of UKFtractography, where it gives the following error:

[ 95%] Performing build step for 'UKFTractography'
Scanning dependencies of target UKFCommonLib
[  3%] Building CXX object common/CMakeFiles/UKFCommonLib.dir/dummy.cc.o
Linking CXX static library /cbica/home/savadjip/software/ukftractography-build/lib/libUKFCommonLib.a
[  3%] Built target UKFCommonLib
[  6%] Generating ConvertVTKCLP.h
GenerateCLP --InputXML /cbica/home/savadjip/software/ukftractography/ukf/ConvertVTK.xml --OutputCxx /cbica/home/savadjip/software/ukftractography-build/UKFTractography-build/ukf/ConvertVTKCLP.h
GenerateCLP: Found 1 parameters groups
GenerateCLP: Group "" has 4 parameters
Scanning dependencies of target ConvertVTKLib
[  9%] Building CXX object ukf/CMakeFiles/ConvertVTKLib.dir/ConvertVTK.cxx.o
Linking CXX static library /cbica/home/savadjip/software/ukftractography-build/lib/libConvertVTKLib.a
[  9%] Built target ConvertVTKLib
Scanning dependencies of target ConvertVTK
[ 12%] Building CXX object ukf/CMakeFiles/ConvertVTK.dir/cbica/home/savadjip/software/ukftractography-build/src/SlicerExecutionModel/CMake/SEMCommandLineLibraryWrapper.cxx.o
make[5]: *** No rule to make target `/usr/lib64/libwrap.so', needed by `/cbica/home/savadjip/software/ukftractography-build/bin/ConvertVTK'.  Stop.
make[4]: *** [ukf/CMakeFiles/ConvertVTK.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [UKFTractography-prefix/src/UKFTractography-stamp/UKFTractography-build] Error 2
make[1]: *** [CMakeFiles/UKFTractography.dir/all] Error 2
make: *** [all] Error 2

Are you guys aware of what this target library '/usr/lib64/libwrap.so' is? Even if it did have the rule to build it, I actually don't have permissions to write under /usr/lib64/ , so to me it feels like a bad idea to have a target directly in /usr/lib64/ ...

As the error seems to occur during the compilation of SEMCommandLineLibraryWrapper.cxx , could this recent commit be related to this error?
https://github.com/pnlbwh/ukftractography/commit/368e301c480c13bc98300c4f576e8514545f3e4e

Any advice/help is much appreciated, thanks!

Peter

**Comment by pnlbwh** [comment]
So to follow up on my hypothesis that the error was caused by the latest commits from this January, I did a
git reset --hard 983fbb0 
which is the latest commit from October before the latest changes to SEMMacroBuild and VTK_Components, and the build worked fine without any errors.

Cheers,
Peter

**Comment by ihnorton** [comment]
Not sure who this was from, but external source builds should work now with recent cmake fixes.

**Comment by Chaircrusher** [comment]
You can take me off this project, I no longer work on VTK/ITK stuff....
