### ISSUE TITLE
Update CMakeLists.txt to use icon located on github

### ISSUE THREAD

**Issue by jcfr** [pnlbwh/ukftractography#63]
Reported-by: @rkikinis

Since the icon hosted on nitrc.org takes some time to be loaded, the extension manager in Slicer time-out and display a default icon.
to help I suggest to update the [description file](https://github.com/Slicer/ExtensionsIndex/blob/94c77ed2b2ca85469b3beaeaa66a828128c9e9ac/UKFTractography.s4ext#L32) to use the icon hosted on a location different from nitrc.org:

http://www.nitrc.org/docman/view.php/425/1223/2TFW_0_128.png

Possible changes to address this:
* [x] Add icon to github and updated description file
* [x] update the [CMakeLists.txt](https://github.com/pnlbwh/ukftractography/blob/master/CMakeLists.txt#L63) to reference the proper url.

**Comment by ihnorton** [comment]
https://github.com/pnlbwh/ukftractography/blob/8cde8e6da41ea12c76c6dedeaa3c21e648e6f5e8/CMakeLists.txt#L63
