### ISSUE TITLE
Compile fails (VNL)

### ISSUE THREAD

**Issue by reckbo** [pnlbwh/ukftractography#76]
I tried compiling with gcc 5.4 and 4.9, and I get this error both times:
```
[  2%] Building CXX object Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o
In file included from /home/reckbo/soft/UKFTractography-build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iosfwd.h:8:0,
                 from /home/reckbo/soft/UKFTractography-build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:27,
                 from /home/reckbo/soft/UKFTractography-build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
/home/reckbo/soft/UKFTractography-build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:130:4: error: #error "Dunno about this gcc"
 #  error "Dunno about this gcc"
    ^
```

**Comment by ihnorton** [comment]
GCC 4.9 is supported and [tested](https://open.cdash.org/buildSummary.php?buildid=4787504) by ITK, so it shouldn't throw that error. Using multiple compilers on the same system can be a little tricky. Make sure that the compiler is actually detected correctly and is using the correct headers.

Support for 5.* is [fixed upstream](https://issues.itk.org/jira/browse/ITK-3361), so we should probably bump the ITK version to what Slicer is using. I'm building that now locally and will push the updated version if there are no issues (should be fine -- Slicer UKF builds are ok).

**Comment by reckbo** [comment]
Works now, thanks.
