### ISSUE TITLE
Extension fail to build on windows

### ISSUE THREAD

**Issue by jcfr** [pnlbwh/ukftractography#8]
See http://slicer.cdash.org/buildSummary.php?buildid=150036

After fixing the issue(s), make sure to regenerate the corresponding extension description file and submit a pull request against both master [1] and 4.3 [2] branch on the extensionsindex.

[ Also notifying @pieper of this issue ]

[1] http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Tutorials/Contribute_Extension_Description_File#Extensions_build_against_Slicer_trunk_2 

[2] http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Tutorials/Contribute_Extension_Description_File#Extensions_build_against_Slicer_4.3_2

**Comment by ihnorton** [comment]
@jcfr can you please enable the extension for the Windows nightly? The Win build issues should be fixed now, mostly thanks to VS2013 (fixing Eigen issues), plus a few small updates (8cde8e6da41ea12c76c6dedeaa3c21e648e6f5e8). It doesn't seem to be built by `factory-south-win7.kitware`, and I'm not sure where the exclusion list is maintained.

**Comment by jcfr** [comment]
* Regarding the order: During the week, Nightly first then 4.5 extensions. Opposite in the weekend. See https://github.com/Slicer/DashboardScripts/blob/master/factory-south-win7.bat

* Now, looking at today dashboard ... the UKF 4.5 extension was built, but the not the Nightly. See http://slicer.cdash.org/index.php?project=Slicer4&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=UKF  I will check the log.

**Comment by ihnorton** [comment]
Any luck? Doesn't seem to have run last night either, and as far as I can tell the other extensions finished already 2+ hours ago on `factory-south-win7.kitware`.

**Comment by jcfr** [comment]
Looking at the factory, their are updates happening in the terminal where the nightly script is running.

That said, there are two things:

* `SlicerApp-real.exe` crashed and is waiting for user to click on "close the program". I looked in the past how to avoid this type of windows but didn't come up with a working solution. Do you know how to avoid them ?

* One of the Reporting extension test is waiting for user input to create a DICOM database. This is blocking.


I don't know if only one or both of these are related to the Nightly build but I suspect this is preventing the Nightly build (or part of it) from going forward ...


![screenshot from 2016-10-07 09-36-50](https://cloud.githubusercontent.com/assets/219043/19191890/403d72ec-8c72-11e6-86e7-4f2c85faaaf2.png)

**Comment by jcfr** [comment]
The blocking popup with the DICOM database is now gone .. but this type of things delay the all build until ctest timeout on a particular test

**Comment by ihnorton** [comment]
Ah, some other extension is hanging and it doesn't even get to UKF?

> SlicerApp-real.exe crashed and is waiting for user to click on "close the program". I looked in the past how to avoid this type of windows but didn't come up with a working solution. Do you know how to avoid them ?

Looks like could set a registry key, `[HKLM|HKCU]\Software\Microsoft\Windows\Windows Error Reporting\DontShowUI` to 1. See http://stackoverflow.com/questions/3561545/how-to-terminate-a-program-when-it-crashes-which-should-just-fail-a-unit-test/3637710#3637710

**Comment by jcfr** [comment]
Two more comments:

* DontShowUI

It was set to `0`, 

![screenshot from 2016-10-07 09-57-25](https://cloud.githubusercontent.com/assets/219043/19192581/acaea49e-8c74-11e6-8460-f6518c1d0311.png)

I just updated it to be one.

![screenshot from 2016-10-07 10-00-02](https://cloud.githubusercontent.com/assets/219043/19192635/d80126da-8c74-11e6-82f3-08880f7c2c00.png)



* Given the implementation of the windows nightly script, nightly build for 4.5 will happen. Error of previous step are ignored.  This is good and it explains why the 4.5 is happening. I will improve the script to log when a step has completed. That way we will now if one is blocking.

**Comment by ihnorton** [comment]
> nightly build for 4.5 will happen.

I don't expect it ever to work on 4.5/Windows, because the related Eigen version can't be built on VS2008. Just want to get it going to current trunk and next release.

**Comment by ihnorton** [comment]
UKF is now available on Windows, as of [3/17 nightly build](http://slicer.cdash.org/buildSummary.php?buildid=989058). (cc @ljod)

Ref: commits to [ExtensionsIndex](https://github.com/Slicer/ExtensionsIndex/commit/03cfdd9ae74ca19ceae26334834123eee73c63cb) and [UKF](https://github.com/pnlbwh/ukftractography/commit/c2df724c3ceb33a603fa852aafceadf349a060de) to eliminate the Eigen(Slicer extension) dependency and instead download Eigen directly (fixes this issue as well as other extension packaging/installation issues on several platforms).

![ukf-windows](https://cloud.githubusercontent.com/assets/327706/24157931/351672ba-0e31-11e7-83ff-15ade1f63066.png)
