### ISSUE TITLE
Build fails because of Eigen dependency

### ISSUE THREAD

**Issue by ysuter** [pnlbwh/ukftractography#94]
I've been trying to build as a standalone version on Ubuntu 16.04, and get an error because of the "Eigen" dependency.
I could previously build it without any issues (last tried around July 2017).
That's the error I get:

```
-- Configuring done
CMake Error at ukf/CMakeLists.txt:91 (add_dependencies):
  The dependency target "Eigen" of target "UKFTractographyLib" does not
  exist.
```
Any help highly appreciated! The Eigen-install -prefix and -build get created, but don't seem to be found.

Best,

Yannick

**Comment by ihnorton** [comment]
@ysuter please do let me know if there is still a problem!
